/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'affiliateLink' : IDL.Text,
  'price' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text], [Category], []),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [Product],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCategory' : IDL.Func([IDL.Nat, IDL.Text], [Category], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [Product],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'affiliateLink' : IDL.Text,
    'price' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text], [Category], []),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [Product],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCategory' : IDL.Func([IDL.Nat, IDL.Text], [Category], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [Product],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };